# Use root/example as user/password credentials
# docker 컴포즈 파일의 버전
version: '3.8'

services:

  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    #restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul


#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 3312:3312